CREATE TABLE IF NOT EXISTS `#__cs_members` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`lname` TEXT,
`fname` TEXT,
`mi` TEXT,
`bname` TEXT,
`title` TEXT,
`address` TEXT,
`city` TEXT,
`state` TEXT,
`zip` TEXT,
`email` TEXT,
`date_entered` DATETIME DEFAULT NULL ,
`by_username` TEXT,
`paidthru` TEXT,
`memtype` TEXT,
`status` TEXT,
`status_updated` DATETIME DEFAULT NULL ,
`last_updated` DATETIME DEFAULT NULL ,
`member_since` DATE DEFAULT NULL ,
`website` TEXT,
`source` TEXT,
`hphone` TEXT,
`wphone` TEXT,
`cphone` TEXT,
`fax` TEXT,
`newsletter_dist` TEXT,
`appl_source` TEXT,
`appl_comments` TEXT,
`appl_duesdue` TEXT,
`appl_paymethod` TEXT,
`created_by` int(11) NOT NULL DEFAULT '279',
`cmsid` int(11) NOT NULL DEFAULT '0',
`forumsid` int(11) NOT NULL DEFAULT '0',
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `#__cs_notes` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`memid` int(11) NOT NULL DEFAULT '0',
`note` text,
`locked` int(11) DEFAULT '1',
`date` datetime DEFAULT NULL,
`by_username` text,
`archived` int(11) NOT NULL DEFAULT '0',
`date_archived` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
`archived_by` text,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;
